# Generated by Django 4.2.6 on 2024-02-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='isSuperUser',
            field=models.BooleanField(default=False),
        ),
    ]
