# Generated by Django 4.2.6 on 2024-02-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser_issuperuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='adminKey',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
