# Generated by Django 4.2.6 on 2024-02-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appuser_adminkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='adminKey',
        ),
    ]
