# Generated by Django 4.2.6 on 2024-03-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_questionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='question_text',
            new_name='text',
        ),
    ]
