# Generated by Django 4.2.6 on 2024-04-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_user_id_usersprogress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersprogress',
            old_name='user',
            new_name='user_id',
        ),
    ]
