# Generated by Django 4.2.6 on 2024-04-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_usersprogress_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='progress',
            field=models.JSONField(default=''),
        ),
        migrations.DeleteModel(
            name='UsersProgress',
        ),
    ]
