# Generated by Django 4.2.6 on 2024-04-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_appuser_position_appuser_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='withOptions',
            field=models.BooleanField(default=False),
        ),
    ]
