# Generated by Django 4.2.6 on 2024-04-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_op1_questionmodel_opt1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='answer',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='opt1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='opt2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='opt3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='opt4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='opt5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
