# Generated by Django 4.2.6 on 2024-04-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_questionmodel_answer_alter_questionmodel_opt1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('background', models.ImageField(default='', upload_to='')),
                ('path', models.JSONField()),
            ],
        ),
    ]
