# Generated by Django 4.2.6 on 2024-04-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_questionmodel_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testmodel'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='background',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
