# Generated by Django 4.2.6 on 2024-04-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_questionmodel_test_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='test_id',
            new_name='testId',
        ),
    ]
