# Generated by Django 4.2.6 on 2024-04-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_test_id_questionmodel_testid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='test_id',
            new_name='testId',
        ),
    ]
