# Generated by Django 4.2.6 on 2024-05-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_testmodel_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='title',
            field=models.CharField(default='Test', max_length=50),
        ),
    ]
