# Generated by Django 4.2.6 on 2024-05-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_testmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='background',
            field=models.ImageField(default='', upload_to='users_avatars'),
        ),
    ]
