# Generated by Django 4.2.6 on 2024-05-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_appuser_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='background',
            new_name='avatar',
        ),
    ]
