# Generated by Django 4.2.6 on 2024-05-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_appuser_activetestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='activeTestId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
