# Generated by Django 4.2.6 on 2024-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_appuser_activetestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='timer',
            field=models.TimeField(default='00:10:00'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
