# Generated by Django 4.2.6 on 2024-05-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_testmodel_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='timer',
            field=models.DateTimeField(default='00'),
        ),
    ]
