# Generated by Django 4.2.6 on 2024-05-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_testmodel_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='currentQuestion',
            field=models.IntegerField(default=1),
        ),
    ]
