# Generated by Django 4.2.6 on 2024-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_testmodel_currentquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='timer',
            field=models.DateTimeField(default='00:00:00'),
        ),
    ]
