# Generated by Django 4.2.6 on 2024-05-19 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_testmodel_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
